// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC670immxekgJWZpk16kxMR-3eWPILemBY',
    appId: '1:63796701074:web:8d43f6522fc00706d2834b',
    messagingSenderId: '63796701074',
    projectId: 'contract-522d7',
    authDomain: 'contract-522d7.firebaseapp.com',
    storageBucket: 'contract-522d7.appspot.com',
    measurementId: 'G-L5RZL6K1HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjBX1KBcNL3zxePGplSmzbyzZ_30F4HSQ',
    appId: '1:63796701074:android:caeee57d241e25d5d2834b',
    messagingSenderId: '63796701074',
    projectId: 'contract-522d7',
    storageBucket: 'contract-522d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBIqjPnVPLIDusD0ipjaLNNC3gX51MtAk',
    appId: '1:63796701074:ios:d6ed38a0e8398c34d2834b',
    messagingSenderId: '63796701074',
    projectId: 'contract-522d7',
    storageBucket: 'contract-522d7.appspot.com',
    iosBundleId: 'com.example.contractList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBIqjPnVPLIDusD0ipjaLNNC3gX51MtAk',
    appId: '1:63796701074:ios:d6ed38a0e8398c34d2834b',
    messagingSenderId: '63796701074',
    projectId: 'contract-522d7',
    storageBucket: 'contract-522d7.appspot.com',
    iosBundleId: 'com.example.contractList',
  );
}
